name: NetraSecure CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Client
        run: |
          cd client
          npm install

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Install Server
        run: |
          cd server
          npm install